### ISSUE TITLE
cannot find "generated" file in o2as_parts_description/urdf

### ISSUE THREAD

**Issue by WangChuang-163** [o2as/ur-o2as#3]
Excuse me，i meet a problem when launch o2as_gazebo.launch with assembly_scene, it cannot find "generated" file in o2as_parts_description/urdf.

**Comment by felixvd** [comment]
You need to run these commands once, as described [here](https://github.com/o2as/ur-o2as/tree/master/catkin_ws/src/o2as_parts_description#generating-the-urdf-files):

```
rosrun o2as_parts_description generate_urdf_from_meshes.py
rosrun o2as_parts_description generate_assembled_piece.py
```

**Comment by WangChuang-163** [comment]
I get it. Thanks for your fast reply!

**Comment by felixvd** [comment]
Sure. Hope the repo is helpful!
