### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by YS-KIT** [o2as/ur-o2as#4]
In file included from proxy.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
Compiling  graph/search.cc                     > /opt/caffe/nccl/build/obj/graph/search.o
In file included from include/core.h:57:0,
                 from include/debug.h:10,
                 from include/checks.h:10,
                 from include/alloc.h:11,
                 from include/gdrwrap.h:148,
                 from misc/gdrwrap.cc:7:

**Comment by felixvd** [comment]
Does this happen in the Docker container? And also, when?

**Comment by felixvd** [comment]
I'll close this for inactivity.
