### ISSUE TITLE
remove the bolts with UR10 robot

### ISSUE THREAD

**Issue by getupcurry** [o2as/ur-o2as#7]
Hi, I want to use a nut tool as the end effector of UR robot to remove the bolts(see figure). Should I use cad_matching method to detect the 6D pose of the bolt? And which part of your project is worth my reference? 
![bolt](https://user-images.githubusercontent.com/46520121/124692037-6e1f9880-df0f-11eb-8159-08550afc1659.jpg)

**Comment by felixvd** [comment]
If you know enough about the geometry, you don't need CAD matching. It can be worth it to confirm that the bolts are removed, but you could also achieve that by other parts of your process. It depends on your situation.

You can have a look at the way that we set up the URDF for a hand-held tool, and the `screw` procedure in `skill_server.cpp` for a reference on how we used end effector frames for these tools. The `taskboard` procedure also uses a nut tool, but does not model it.

Hope that helps.

**Comment by getupcurry** [comment]
Thank you! Can you give me some ideas on how to detect the 6D pose of the bolt head?

**Comment by felixvd** [comment]
Pose estimation is an open problem with many commercially available and research solutions. It's not covered by this repository, but generally I would consider the type of data you want to use (RGB? Depth?), the precision you expect and require, and if you really need to estimate unconstrained 6D poses in your process.

If you can simplify the problem to a binary yes/no check, it becomes a lot easier (e.g. if you know the position of the part, move a camera above each bolt and check "Is a bolt in the view?", then attempt to remove it or not. Or try to close the gripper around the bolt or touch it to see if it is physically there)

The vision system is not part of this repository though, and it's not my field of expertise, so I'll leave it at that.
